# Generated by Django 5.0.3 on 2024-03-22 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address_1', models.CharField(max_length=150)),
                ('address_2', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=5)),
                ('zip_plus', models.CharField(max_length=4)),
                ('phone', models.CharField(max_length=18)),
                ('country_code', models.CharField(max_length=4)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address_1', models.CharField(max_length=150)),
                ('address_2', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=5)),
                ('zip_plus', models.CharField(max_length=4)),
                ('phone', models.CharField(max_length=18)),
                ('country_code', models.CharField(max_length=4)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('tote_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDispatchLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address_1', models.CharField(max_length=150)),
                ('address_2', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=5)),
                ('zip_plus', models.CharField(max_length=4)),
                ('phone', models.CharField(max_length=18)),
                ('country_code', models.CharField(max_length=4)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avantecore.customer')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=100)),
                ('sensor_type', models.CharField(choices=[('TOF', 'Time of Flight / ToF'), ('AMBTMP', 'Ambient Temperature'), ('HUMID', 'Humidity'), ('O2', 'Oxygen / O2'), ('LOC', 'Location/ GPS')], max_length=10)),
                ('serial_num', models.CharField(max_length=150)),
                ('eth0', models.CharField(max_length=17)),
                ('note', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='djangouploads/files/sensor_images')),
                ('customer_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avantecore.customerdispatchlocation')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('tote_reference', models.CharField(max_length=50)),
                ('distance', models.FloatField()),
                ('humidity', models.SmallIntegerField()),
                ('temperature', models.SmallIntegerField()),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avantecore.environmentsensor')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avantecore.provider'),
        ),
        migrations.CreateModel(
            name='ProviderDispatchLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address_1', models.CharField(max_length=150)),
                ('address_2', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=5)),
                ('zip_plus', models.CharField(max_length=4)),
                ('phone', models.CharField(max_length=18)),
                ('country_code', models.CharField(max_length=4)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avantecore.provider')),
            ],
        ),
        migrations.CreateModel(
            name='HaulEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('dispatch_location', models.CharField(max_length=100)),
                ('totes_on_trailer', models.SmallIntegerField()),
                ('weight_on_trailer', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dispatch_location_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avantecore.providerdispatchlocation')),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_id', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('scale_type', models.CharField(max_length=150)),
                ('serial_num', models.CharField(max_length=150)),
                ('eth0', models.CharField(max_length=17)),
                ('note', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='djangouploads/files/scale_images')),
                ('customer_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avantecore.customerdispatchlocation')),
            ],
        ),
        migrations.CreateModel(
            name='ScaleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('lbs_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('field00', models.CharField(max_length=150)),
                ('field01', models.CharField(max_length=150)),
                ('field02', models.CharField(max_length=150)),
                ('field04', models.CharField(max_length=150)),
                ('tote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avantecore.tote')),
            ],
        ),
        migrations.CreateModel(
            name='ToteMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=150)),
                ('tote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avantecore.tote')),
            ],
        ),
    ]
