# Generated by Django 4.2.9 on 2024-06-14 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avantecore', '0002_haulentrydocument_scaleentrydocument'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnvironmentSensor',
            new_name='SmartEdgeSensor',
        ),
    ]
