# Generated by Django 4.2.9 on 2024-06-14 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avantecore', '0003_rename_environmentsensor_smartedgesensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTBoardFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_spirit_code', models.CharField(max_length=10)),
                ('feature_name', models.CharField(max_length=50)),
                ('feature_description', models.CharField(max_length=250)),
                ('feature_type', models.CharField(choices=[('CTRLR', 'Microcontroller'), ('SNSRTYPE', 'Sensory'), ('CRYPTO', 'Cryptogaphy'), ('COMM', 'I/O')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='smartedgesensor',
            name='eth0',
        ),
        migrations.RemoveField(
            model_name='smartedgesensor',
            name='note',
        ),
        migrations.RemoveField(
            model_name='smartedgesensor',
            name='sensor_type',
        ),
        migrations.AddField(
            model_name='smartedgesensor',
            name='btle_mac',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='smartedgesensor',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartedgesensor',
            name='eth0_mac',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='smartedgesensor',
            name='eth1_mac',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='smartedgesensor',
            name='sensor_name',
            field=models.CharField(default='No Name Provided', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smartedgesensor',
            name='image',
            field=models.ImageField(null=True, upload_to='djangouploads/filessensor_images'),
        ),
        migrations.AlterField(
            model_name='smartedgesensor',
            name='serial_num',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='IoTBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_nickname', models.CharField(max_length=100)),
                ('board_type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='djangouploads/files/sensor_images')),
                ('board_features', models.ManyToManyField(null=True, to='avantecore.iotboardfeatures')),
            ],
        ),
        migrations.AddField(
            model_name='smartedgesensor',
            name='sensor_iot_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avantecore.iotboard'),
        ),
    ]
