# Generated by Django 4.2.9 on 2024-06-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avantecore', '0004_iotboardfeatures_remove_smartedgesensor_eth0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotboard',
            name='image',
            field=models.ImageField(null=True, upload_to='djangouploads/files/sensor_images'),
        ),
        migrations.AlterField(
            model_name='iotboardfeatures',
            name='feature_type',
            field=models.CharField(choices=[('CTRLR', 'Microcontroller'), ('SNSRTYPE', 'Environmental/Sensory'), ('CRYPTO', 'Cryptogaphy'), ('COMM', 'I/O')], max_length=10),
        ),
    ]
