# Generated by Django 4.2.9 on 2024-06-17 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avantecore', '0008_ledgerentry_customer_spirit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('staged_totes', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='haulentry',
            name='totes_in_staging',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tote',
            name='staged',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avantecore.logisticsstate'),
        ),
    ]
