# Generated by Django 4.2.9 on 2024-06-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avantecore', '0011_logisticsstate_closed_on_totemove_ledger_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsstate',
            name='staged_totes_calculated',
            field=models.SmallIntegerField(default=0),
        ),
    ]
