# Generated by Django 4.2.9 on 2024-07-09 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avantecore', '0014_rename_staged_totes_logisticsstate_staged_totes_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsstate',
            name='logistics_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tote',
            name='active_tote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tote',
            name='tote_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='totemove',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='avantecore.smartedgesensor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logisticsstate',
            name='staged_totes_manual',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='scale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='djangouploads/files/scale_images'),
        ),
    ]
